---
title: "mag_sapp_shared"
params:
  use_local: true 
  data_file: "temp_data.csv"
---

```{r}
#install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
library(here)
library(janitor)
library(dplyr)
library(usethis)
use_git()

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010" # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"
temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate) |>
renameNWISColumns()

write_csv(temp_data, "temp_data.csv") 

# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")

# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)

temp_data <- temp_data |>
  select(-5)

temp_data |>
group_by(site_no) |>
  summarize(mean_temp = mean(temp_C, na.rm = TRUE), 
            max_temp = max(temp_C, na.rm = TRUE),
            min_temp = min(temp_C, na.rm = TRUE))


# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()
  
```

## Alicia Magliato Analysis: August

```{r}
# filter for August temperatures
august_data <- subset(temp_data, month == "Aug")
# fit a GLM model to see if there is a trend in August temperatures over time, separated by site
august_model <- glm(temp_C ~ year*site_no, data = august_data)
summary(august_model)
```


## Kalena Sapp Analysis: February

```{r}
library(tidyverse)
# filter for Feb temperatures
feb_data <- subset(temp_data, month == "Feb")
# fit a GLM model to see if there is a trend in Feb temperatures over time, separated by site
feb_model <- glm(temp_C ~ year*site_no, data = feb_data)
summary(feb_model)
```

## August and February Warming Trendlines 2010-2023 

```{r}

ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites in February and August from 2010 to 2023",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()

```






























```{r}
combined_data <- temp_data |>
  filter(month %in% c("Aug", "Feb"))

ggplot(combined_data, aes(x = year, y = temp_C, color = site_no)) +
  geom_point(alpha = 0.4) +                 
  geom_smooth(method = "glm", se = FALSE) + 
  facet_wrap(~month, scales = "free_y") +   
  labs(title = "Temperature Trends: August vs. February",
       x = "Year",
       y = "Temperature (°C)",
       color = "Site Number") +
  theme_minimal()


```





